server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://106.14.176.2:demo?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
  application:
    name:
      demo
  profiles:
    active: dev
